unit FichaEstoque;

interface

uses System.SysUtils, Data.DB, FireDAC.Comp.Client, MainModule, funcoes, uniguiDialogs;

//procedure ProcessaFichas(pFicha: TFDQuery; pCodEmp: integer; pNomeEmp, pCNPJEmp: String; pDesc: integer; pProdutos: string);
procedure ProcessaFichas(pCodEmp: integer; pNomeEmp, pCNPJEmp: String; pDesc, pNota: integer; pProdutos, pOrigem: string);
                                    
implementation

procedure ProcessaFichas(pCodEmp: integer; pNomeEmp, pCNPJEmp: String; pDesc, pNota: integer; pProdutos, pOrigem: string);
var
  mscript: widestring;
  Ficha: TFDQuery;
begin
     Ficha := TFDQuery.Create(nil);
     try
        Ficha.Connection := uniMainModule.Conecta;
        with Ficha do begin
             sql.Clear;
             sql.Add('set nocount on;');
             sql.Add('set xact_abort ON;');
             sql.Add('begin transaction;');
             sql.Add('if object_id(''tempdb..#TEMPDT'') is not null drop table #tempdt;');
             sql.Add('if object_id(''tempdb..#TEMP'') is not null drop table #temp;');
             sql.Add('if object_id(''tempdb..#TEMP2'') is not null drop table #temp2;');
             sql.Add('if object_id(''FichaEstoque'',''U'') is not null begin');
             if trim(pProdutos) = '' then begin
                sql.Add('   truncate table FichaEstoque');
             end else begin
                sql.Add('   delete from FichaEstoque where Nota_id = :pNota and Origem = :pOrigem');
             end;
             sql.Add('end;');
             sql.Add('select min(Data_Emissao) as Data into #tempdt from NotasFiscais where Cancelada <> 1 and Denegada <> 1 and Provisoria <> 1');
             sql.Add('union all');
             sql.Add('select min(Data_Transferencia) from EstoqueTransferencia');
             sql.Add('union all');
             sql.Add('select min(Data_Entrada) from EstoqueAbertura');
             sql.Add('union all');
             sql.Add('select min(Data) from Industrializacao;');
             sql.Add('delete from #tempdt where Data is null;');
             sql.Add('declare @Menor_Data datetime;');
             sql.Add('declare @Maior_Data datetime;');
             sql.Add('select @Menor_Data = min(Data), @Maior_Data = getdate() from #tempdt;');
             sql.Add('----------------------------- NOTAS FISCAIS DE ENTRADA E SAÍDA -------------------------------------');
             sql.Add('select ni.Codigo_Mercadoria');
             sql.Add('      ,Descricao = cast(iif(:pDesc = 0, ni.Descricao_Mercadoria, p.Descricao) as varchar(500))');
             sql.Add('      ,UM = ni.UM');
             sql.Add('      ,NCM = ni.NCM');
             sql.Add('      ,ni.CFOP');
             sql.Add('      ,Historico = upper(cast(fn.Descricao as varchar(70)))');
             sql.Add('      ,Estoque   = upper(cast(fn.Estoque as varchar(10)))');
             sql.Add('      ,Nota = nf.Nota');
             sql.Add('      ,Data = nf.Data_Emissao');
             sql.Add('      ,Destinatario_Codigo = nf.Destinatario');
             sql.Add('      ,Destinatario_Nome = nf.Destinatario_Nome');
             sql.Add('      ,Destinatario_CNPJ = nf.Destinatario_CNPJ_CPF');
             sql.Add('      ,Finalidade = op.Finalidade_Mercadoria');
             sql.Add('      ,ES = iif(nf.ES = 0, ''E'', ''S'')');
             sql.Add('      ,Processo = ni.Processo');
             sql.Add('      ,pd.Modalidade');
             sql.Add('      ,Qtde_Entrada = iif(nf.ES = 0, isnull(ni.Quantidade, 0), 0)');
             sql.Add('      ,Unitario_Entrada = iif(nf.ES = 0, round(isnull(ni.Valor_Inventario, 0), 4), 0)');
             sql.Add('      ,Total_Entrada = iif(nf.ES = 0, round(isnull(ni.Valor_Inventario, 0), 2) * ni.Quantidade, 0)');
             sql.Add('      ,Qtde_Saida = iif(nf.ES = 1, isnull(ni.Quantidade, 0), 0)');
             sql.Add('      ,Unitario_Saida = iif(nf.ES = 1, round(isnull(ni.Valor_Inventario, 0), 4), 0)');
             sql.Add('      ,Total_Saida = iif(nf.ES = 1, round(isnull(ni.Valor_Inventario, 0), 2) * ni.Quantidade, 0)');
             sql.Add('      ,Qtde_Saldo = cast(0 as decimal(18,3))');
             sql.Add('      ,Unitario_Saldo = cast(0 as decimal(18,4))');
             sql.Add('      ,Total_Saldo = cast(0 as decimal(18,4))');
             sql.Add('      ,Emissor = nf.Emissao');
             sql.Add('      ,Origem = cast(''NFE'' as char(3))');
             sql.Add('      ,nf.Empresa');
             sql.Add('      ,ni.Nota_id');
             sql.Add('      ,Item_Nota = ni.Item');
             sql.Add('into #temp');
             sql.Add('from NotasItens ni');
             sql.Add('inner join NotasFiscais nf on nf.Nota_id = ni.Nota_id');
             sql.Add('left join Produtos p on p.Codigo = ni.Codigo_Mercadoria');
             sql.Add('left join OperacaoFiscal op on op.Codigo = nf.Operacao');
             sql.Add('left join FinalidadesMercadorias fn on fn.Codigo = op.Finalidade_Mercadoria');
             sql.Add('outer apply (select top 1 pd.Modalidade from ProcessosImp pd where pd.Processo = ni.Processo) pd');
             sql.Add('where nf.Empresa = :pCNPJEmp');
             if trim(pProdutos) <> '' then begin
                sql.Add('and ni.Codigo_Mercadoria in('+pProdutos+')');
             end;
             sql.Add('and ni.Valor_Unitario > 0');
             sql.Add('and nf.Cancelada <> 1');
             sql.Add('and nf.Denegada <> 1');
             sql.Add('and (op.Movimenta_Estoque = 1 or nf.Complementar = 1);');
             sql.Add('----------------------------- ABERTURA DE ESTOQUE -----------------------------');
             sql.Add('insert into #temp');
             sql.Add('select Codigo_Mercadoria = ea.Codigo_Mercadoria');
             sql.Add('      ,Descricao = cast(p.Descricao as varchar(500))');
             sql.Add('      ,p.UM');
             sql.Add('      ,NCM = p.NCM');
             sql.Add('      ,ea.CFOP');
             sql.Add('      ,Historico = ''<< SALDO DE ABERTURA DE ESTOQUE >>''');
             sql.Add('      ,Estoque = ''0-EMPRESA''');
             sql.Add('      ,Nota = ea.Nota');
             sql.Add('      ,Data = ea.Data_Entrada');
             sql.Add('      ,Destinatario_Codigo = :pCodEmp');
             sql.Add('      ,Destinatario_Nome = :pNomeEmp');
             sql.Add('      ,Destinatario_CNPJ = :pCNPJEmp');
             sql.Add('      ,Finalidade = 0');
             sql.Add('      ,ES = ''E''');
             sql.Add('      ,ea.Processo');
             sql.Add('      ,pd.Modalidade');
             sql.Add('      ,Qtde_Entrada = ea.Quantidade');
             sql.Add('      ,Unitario_Entrada = ea.Valor_Unitario');
             sql.Add('      ,Total_Entrada = ea.Valor_Unitario * ea.Quantidade');
             sql.Add('      ,Qtde_Saida = cast(0 as float)');
             sql.Add('      ,Unitario_Saida = cast(0 as float)');
             sql.Add('      ,Total_Saida = cast(0 as float)');
             sql.Add('      ,Qtde_Saldo = cast(0 as float)');
             sql.Add('      ,Unitario_Saldo = cast(0 as float)');
             sql.Add('      ,Total_Saldo = cast(0 as float)');
             sql.Add('      ,Emissor = ''P''');
             sql.Add('      ,Origem = ''ABR''');
             sql.Add('      ,ea.Empresa');
             sql.Add('      ,Nota_id = isnull(ea.Nota, 0)');
             sql.Add('      ,Item_Nota = 1');
             sql.Add('from EstoqueAbertura ea');
             sql.Add('left join Produtos p on p.Codigo = ea.Codigo_Mercadoria');
             sql.Add('outer apply (select top 1 pd.Modalidade from ProcessosImp pd where pd.Processo = ea.Processo) pd');
             sql.Add('where ea.Empresa = :pCNPJEmp');
             if trim(pProdutos) <> '' then begin
                sql.Add('and ea.Codigo_Mercadoria in('+pProdutos+')');
             end;
             sql.Add('----------------------------- TRANSFERÊNCIAS DE ESTOQUE -----------------------------');
             sql.Add('insert into #temp');
             sql.Add('select Codigo_Mercadoria = x.Codigo_Mercadoria');
             sql.Add('      ,Descricao = cast(p.Descricao as varchar(500))');
             sql.Add('      ,p.UM');
             sql.Add('      ,NCM = p.NCM');
             sql.Add('      ,pt.CFOP');
             sql.Add('      ,Historico = ''<< TRANSFERÊNCIA DE SALDO DE ESTOQUE >>''');
             sql.Add('      ,Estoque = ''0-EMPRESA''');
             sql.Add('      ,Nota = iif(isnull(pt.Nota,0) = 0, pt.Registro, pt.Nota)');
             sql.Add('      ,Data = pt.Data_Transferencia');
             sql.Add('      ,Destinatario_Codigo = :pCodEmp');
             sql.Add('      ,Destinatario_Nome = :pNomeEmp');
             sql.Add('      ,Destinatario_CNPJ = :pCNPJEmp');
             sql.Add('      ,Finalidade = 0');
             sql.Add('      ,ES = x.ES');
             sql.Add('      ,Processo = x.Processo');
             sql.Add('      ,pd.Modalidade');
             sql.Add('      ,Qtde_Entrada = case when x.ES = ''E'' then x.Quantidade else cast(0 as float) end');
             sql.Add('      ,Unitario_Entrada = case when x.ES = ''E'' then round(pt.Valor_Unitario,2) else cast(0 as float) end');
             sql.Add('      ,Total_Entrada = case when x.ES = ''E'' then round(pt.Valor_Unitario,2) * x.Quantidade else cast(0 as float) end');
             sql.Add('      ,Qtde_Saida = case when x.ES = ''S'' then x.Quantidade else cast(0 as float) end');
             sql.Add('      ,Unitario_Saida = case when x.ES = ''S'' then round(pt.Valor_Unitario,2) else cast(0 as float) end');
             sql.Add('      ,Total_Saida = case when x.ES = ''S'' then round(pt.Valor_Unitario,2) * x.Quantidade else cast(0 as float) end');
             sql.Add('      ,Qtde_Saldo = cast(0 as float)');
             sql.Add('      ,Unitario_Saldo = cast(0 as float)');
             sql.Add('      ,Total_Saldo = cast(0 as float)');
             sql.Add('      ,Emissor = ''P''');
             sql.Add('      ,Origem = ''TRF''');
             sql.Add('      ,pt.Empresa');
             sql.Add('      ,Nota_id = pt.Registro');
             sql.Add('      ,Item_Nota = 1');
             sql.Add('from EstoqueTransferencia pt');
             sql.Add('cross apply (values (pt.Produto_Entrada, pt.Quantidade_Entrada, pt.Processo_Entrada, ''E''), (pt.Produto_Saida, pt.Quantidade_Saida, pt.Processo_Saida, ''S'')) x(Codigo_Mercadoria, Quantidade, Processo, ES)');
             sql.Add('left join Produtos p on p.Codigo = x.Codigo_Mercadoria');
             sql.Add('outer apply (select top 1 pd.Modalidade from ProcessosImp pd where pd.Processo = x.Processo) pd');
             sql.Add('where pt.Empresa = :pCNPJEmp');
             if trim(pProdutos) <> '' then begin
                sql.Add('and (pt.Produto_Entrada in('+pProdutos+') or pt.Produto_Saida in('+pProdutos+'))');
             end;
             sql.Add('and pt.Movimenta_Estoque = 1');
             sql.Add('and isnull(x.Codigo_Mercadoria,0) <> 0;');
             sql.Add('----------------------------- INDUSTRIALIZAÇÃO - ENTRADAS DE PRODUTO INDUSTRIALIZADO -------------------------------------');
             sql.Add('insert into #temp');
             sql.Add('select Codigo_Mercadoria = ind.Codigo_Mercadoria');
             sql.Add('      ,Descricao = cast(p.Descricao as varchar(500))');
             sql.Add('      ,p.UM');
             sql.Add('      ,NCM = p.NCM');
             sql.Add('      ,ind.CFOP');
             sql.Add('      ,Historico = ''<< ENTRADA DE PRODUTO INDUSTRIALIZADO >>''');
             sql.Add('      ,Estoque = ''0-EMPRESA''');
             sql.Add('      ,Nota = ind.Registro');
             sql.Add('      ,ind.Data');
             sql.Add('      ,Destinatario_Codigo = ind.Destinatario');
             sql.Add('      ,Destinatario_Nome = d.Nome');
             sql.Add('      ,Destinatario_CNPJ = d.CNPJ');
             sql.Add('      ,Finalidade = 0');
             sql.Add('      ,ES = ''E''');
             sql.Add('      ,ind.Processo');
             sql.Add('      ,pd.Modalidade');
             sql.Add('      ,Qtde_Entrada = ind.Quantidade');
             sql.Add('      ,Unitario_Entrada = ind.Valor_Unitario');
             sql.Add('      ,Total_Entrada = round(ind.Valor_Unitario * ind.Quantidade, 3)');
             sql.Add('      ,Qtde_Saida = cast(0 as float)');
             sql.Add('      ,Unitario_Saida = cast(0 as float)');
             sql.Add('      ,Total_Saida = cast(0 as float)');
             sql.Add('      ,Qtde_Saldo = cast(0 as float)');
             sql.Add('      ,Unitario_Saldo = cast(0 as float)');
             sql.Add('      ,Total_Saldo = cast(0 as float)');
             sql.Add('      ,Emissor = ''P''');
             sql.Add('      ,Origem = ''IND''');
             sql.Add('      ,ind.Empresa');
             sql.Add('      ,Nota_id = ind.Registro');
             sql.Add('      ,Item_Nota = 1');
             sql.Add('from Industrializacao ind');
             sql.Add('left join Produtos p on p.Codigo = ind.Codigo_Mercadoria');
             sql.Add('left join Destinatarios d on d.Codigo = ind.Destinatario');
             sql.Add('outer apply (select top 1 pd.Modalidade from ProcessosImp pd where pd.Processo = ind.Processo) pd');
             sql.Add('where ind.Empresa = :pCNPJEmp');
             if trim(pProdutos) <> '' then begin
                sql.Add('and ind.Registro = :pNota');
                sql.Add('and ind.Codigo_Mercadoria in('+pProdutos+')');
             end;
             sql.Add('----------------------------- INDUSTRIALIZAÇÃO - SAÍDA DE MATÉRIA-PRIMAS -------------------------------------');
             sql.Add('insert into #temp');
             sql.Add('select Codigo_Mercadoria = im.Codigo_Mercadoria');
             sql.Add('      ,Descricao = cast(p.Descricao as varchar(500))');
             sql.Add('      ,p.UM');
             sql.Add('      ,NCM = p.NCM');
             sql.Add('      ,ind.CFOP');
             sql.Add('      ,Historico = ''<< SAÍDA DE MATÉRIAS-PRIMAS INDUSTRALIZAÇÃO >>''');
             sql.Add('      ,Estoque = ''0-EMPRESA''');
             sql.Add('      ,Nota = im.Registro_id');
             sql.Add('      ,ind.Data');
             sql.Add('      ,Destinatario_Codigo = ind.Destinatario');
             sql.Add('      ,Destinatario_Nome = d.Nome');
             sql.Add('      ,Destinatario_CNPJ = d.CNPJ');
             sql.Add('      ,Finalidade = 0');
             sql.Add('      ,ES = ''S''');
             sql.Add('      ,ind.Processo');
             sql.Add('      ,pd.Modalidade');
             sql.Add('      ,Qtde_Entrada = 0');
             sql.Add('      ,Unitario_Entrada = 0');
             sql.Add('      ,Total_Entrada = 0');
             sql.Add('      ,Qtde_Saida = im.Quantidade_Total');
             sql.Add('      ,Unitario_Saida = im.Valor_Unitario');
             sql.Add('      ,Total_Saida = round(im.Valor_Unitario * im.Quantidade_Total, 3)');
             sql.Add('      ,Qtde_Saldo = cast(0 as float)');
             sql.Add('      ,Unitario_Saldo = cast(0 as float)');
             sql.Add('      ,Total_Saldo = cast(0 as float)');
             sql.Add('      ,Emissor = ''P''');
             sql.Add('      ,Origem = ''IND''');
             sql.Add('      ,ind.Empresa');
             sql.Add('      ,Nota_id = im.Registro_id');
             sql.Add('      ,Item_Nota = 1');
             sql.Add('from IndustrializacaoMateria im');
             sql.Add('left join Industrializacao ind on ind.Registro = im.Registro_id');
             sql.Add('left join Produtos p on p.Codigo = im.Codigo_Mercadoria');
             sql.Add('left join Destinatarios d on d.Codigo = ind.Destinatario');
             sql.Add('outer apply (select top 1 pd.Modalidade from ProcessosImp pd where pd.Processo = ind.Processo) pd');
             sql.Add('where ind.Empresa = :pCNPJEmp');
             if trim(pProdutos) <> '' then begin
                sql.Add('and ind.Registro = :pNota');
                sql.Add('and im.Codigo_Mercadoria in('+pProdutos+')');
             end;
             sql.Add('create clustered index ix_temp_cod_data on #temp (Codigo_Mercadoria, Data, ES, Nota);');
             sql.Add('select Linha = row_number() over (order by Codigo_Mercadoria, Data, ES, Nota)');
             sql.Add('      ,Item = row_number() over (partition by Codigo_Mercadoria order by Data, ES, Nota)');
             sql.Add('      ,*');
             sql.Add('into #temp2');
             sql.Add('from #temp;');
             sql.Add('create clustered index ix_temp2_cod_item on #temp2 (Codigo_Mercadoria, Item);');
             sql.Add('with Estoque as (');
             sql.Add('   select t.Linha');
             sql.Add('         ,t.Empresa');
             sql.Add('         ,t.Item');
             sql.Add('         ,t.Codigo_Mercadoria');
             sql.Add('         ,t.NCM');
             sql.Add('         ,t.Descricao');
             sql.Add('         ,t.UM');
             sql.Add('         ,t.CFOP');
             sql.Add('         ,t.Historico');
             sql.Add('         ,t.Estoque');
             sql.Add('         ,t.Emissor');
             sql.Add('         ,t.Origem');
             sql.Add('         ,t.Nota_id');
             sql.Add('         ,t.Nota');
             sql.Add('         ,t.Data');
             sql.Add('         ,t.Item_Nota');
             sql.Add('         ,t.ES');
             sql.Add('         ,t.Destinatario_Codigo');
             sql.Add('         ,t.Destinatario_Nome');
             sql.Add('         ,t.Destinatario_CNPJ');
             sql.Add('         ,t.Finalidade');
             sql.Add('         ,t.Processo');
             sql.Add('         ,t.Modalidade');
             sql.Add('         ,t.Qtde_Entrada');
             sql.Add('         ,t.Unitario_Entrada');
             sql.Add('         ,t.Total_Entrada');
             sql.Add('         ,Qtde_Saida = T.Qtde_Saida');
             sql.Add('         ,Unitario_Saida = cast(0 as float)');
             sql.Add('         ,Total_Saida = cast(0 as float)');
             sql.Add('         ,Qtde_Saldo = cast(round(T.Qtde_Entrada - T.Qtde_Saida, 3) as decimal(18,3))');
             sql.Add('         ,Total_Saldo = cast(T.Total_Entrada - T.Total_Saida as float)');
             sql.Add('         ,Unitario_Saldo = cast(iif(T.Qtde_Entrada - T.Qtde_Saida > 0, (T.Total_Entrada - T.Total_Saida) / (T.Qtde_Entrada - T.Qtde_Saida), 0) as float)');
             sql.Add('   from #TEMP2 T');
             sql.Add('   where T.Item = 1');
             sql.Add('   union all');
             sql.Add('   select t.Linha');
             sql.Add('         ,t.Empresa');
             sql.Add('         ,t.Item');
             sql.Add('         ,t.Codigo_Mercadoria');
             sql.Add('         ,t.NCM');
             sql.Add('         ,t.Descricao');
             sql.Add('         ,t.UM');
             sql.Add('         ,t.CFOP');
             sql.Add('         ,t.Historico');
             sql.Add('         ,t.Estoque');
             sql.Add('         ,t.Emissor');
             sql.Add('         ,t.Origem');
             sql.Add('         ,t.Nota_id');
             sql.Add('         ,t.Nota');
             sql.Add('         ,t.Data');
             sql.Add('         ,t.Item_Nota');
             sql.Add('         ,t.ES');
             sql.Add('         ,t.Destinatario_Codigo');
             sql.Add('         ,t.Destinatario_Nome');
             sql.Add('         ,t.Destinatario_CNPJ');
             sql.Add('         ,t.Finalidade');
             sql.Add('         ,t.Processo');
             sql.Add('         ,t.Modalidade');
             sql.Add('         ,t.Qtde_Entrada');
             sql.Add('         ,t.Unitario_Entrada');
             sql.Add('         ,t.Total_Entrada');
             sql.Add('         ,Qtde_Saida = T.Qtde_Saida');
             sql.Add('         ,Unitario_Saida = cast(e.Unitario_Saldo as float)');
             sql.Add('         ,Total_Saida = cast(e.Unitario_Saldo * t.Qtde_Saida as float)');
             sql.Add('         ,Qtde_Saldo = cast(round(E.Qtde_Saldo + t.Qtde_Entrada - t.Qtde_Saida, 3) as decimal(18,3))');
             sql.Add('         ,Total_Saldo = cast(case when e.Qtde_Saldo + t.Qtde_Entrada - t.Qtde_Saida > 0 then');
             sql.Add('                                    case when t.ES = ''E'' then');
             sql.Add('                                         e.Total_Saldo + t.Total_Entrada');
             sql.Add('                                    else');
             sql.Add('                                         e.Total_Saldo - (e.Unitario_Saldo * t.Qtde_Saida)');
             sql.Add('                                    end');
             sql.Add('                                else');
             sql.Add('                                    0');
             sql.Add('                                end as float)');
             sql.Add('         ,Unitario_Saldo = cast(case when e.Qtde_Saldo + t.Qtde_Entrada - t.Qtde_Saida > 0 then');
             sql.Add('                                     case when t.ES = ''E'' then');
             sql.Add('                                          (e.Total_Saldo + t.Total_Entrada) / (e.Qtde_Saldo + t.Qtde_Entrada)');
             sql.Add('                                     else');
             sql.Add('                                          (e.Total_Saldo - (e.Unitario_Saldo * t.Qtde_Saida)) / (e.Qtde_Saldo - t.Qtde_Saida)');
             sql.Add('                                     end');
             sql.Add('                                else');
             sql.Add('                                     0');
             sql.Add('                                end as float)');
             sql.Add('   from Estoque e');
             sql.Add('   inner join #temp2 t on t.Codigo_Mercadoria = e.Codigo_Mercadoria and t.Item = e.Item + 1)');
             sql.Add('insert into FichaEstoque(');
             sql.Add('       Empresa');
             sql.Add('      ,Item');
             sql.Add('      ,Codigo_Mercadoria');
             sql.Add('      ,NCM');
             sql.Add('      ,Descricao');
             sql.Add('      ,UM');
             sql.Add('      ,CFOP');
             sql.Add('      ,Historico');
             sql.Add('      ,Estoque');
             sql.Add('      ,Emissor');
             sql.Add('      ,Origem');
             sql.Add('      ,Nota_id');
             sql.Add('      ,Nota');
             sql.Add('      ,Data');
             sql.Add('      ,Item_Nota');
             sql.Add('      ,ES');
             sql.Add('      ,Destinatario_Codigo');
             sql.Add('      ,Destinatario_Nome');
             sql.Add('      ,Destinatario_CNPJ');
             sql.Add('      ,Finalidade');
             sql.Add('      ,Processo');
             sql.Add('      ,Modalidade');
             sql.Add('      ,Qtde_Entrada');
             sql.Add('      ,Unitario_Entrada');
             sql.Add('      ,Total_Entrada');
             sql.Add('      ,Qtde_Saida');
             sql.Add('      ,Unitario_Saida');
             sql.Add('      ,Total_Saida');
             sql.Add('      ,Qtde_Saldo');
             sql.Add('      ,Unitario_Saldo');
             sql.Add('      ,Total_Saldo)');
             sql.Add('select Empresa');
             sql.Add('      ,Item');
             sql.Add('      ,Codigo_Mercadoria');
             sql.Add('      ,NCM');
             sql.Add('      ,Descricao');
             sql.Add('      ,UM');
             sql.Add('      ,CFOP');
             sql.Add('      ,Historico');
             sql.Add('      ,Estoque');
             sql.Add('      ,Emissor');
             sql.Add('      ,Origem');
             sql.Add('      ,Nota_id');
             sql.Add('      ,Nota');
             sql.Add('      ,Data');
             sql.Add('      ,Item_Nota');
             sql.Add('      ,ES');
             sql.Add('      ,Destinatario_Codigo');
             sql.Add('      ,ltrim(rtrim(Destinatario_Nome))');
             sql.Add('      ,Destinatario_CNPJ');
             sql.Add('      ,Finalidade');
             sql.Add('      ,Processo');
             sql.Add('      ,Modalidade');
             sql.Add('      ,Qtde_Entrada');
             sql.Add('      ,Unitario_Entrada');
             sql.Add('      ,Total_Entrada');
             sql.Add('      ,Qtde_Saida');
             sql.Add('      ,Unitario_Saida');
             sql.Add('      ,Total_Saida');
             sql.Add('      ,Qtde_Saldo');
             sql.Add('      ,Unitario_Saldo');
             sql.Add('      ,Total_Saldo');
             sql.Add('from Estoque');
             sql.Add('order by Codigo_Mercadoria, Data, ES, Nota');
             sql.Add('option (maxrecursion 0);');
             sql.Add('drop table #temp2;');
             sql.Add('drop table #temp;');
             sql.Add('drop table #tempdt;');
             sql.Add('commit transaction;');
             parambyname('pDesc').AsInteger := pDesc;
             parambyname('pCodEmp').AsInteger := pCodEmp;
             parambyname('pNomeEmp').AsString := pNomeEmp;
             parambyname('pCNPJEmp').AsString := pCNPJEmp;
             if trim(pProdutos) <> '' then begin
                parambyname('pNota').AsInteger := pNota;
                parambyname('pOrigem').AsString := pOrigem;
             end;
             mscript := stringreplace(sql.Text, 'FichaEstoque', 'FichaInventario', [rfReplaceAll]);
             mscript := stringreplace(mscript, 'Movimenta_Estoque', 'Movimenta_Inventario', [rfReplaceAll]);
             execsql;
             sql.Clear;
             sql.Add(mscript);
             parambyname('pDesc').AsInteger := pDesc;
             parambyname('pCodEmp').AsInteger := pCodEmp;
             parambyname('pNomeEmp').AsString := pNomeEmp;
             parambyname('pCNPJEmp').AsString := pCNPJEmp;
             if trim(pProdutos) <> '' then begin
                parambyname('pNota').AsInteger := pNota;
                parambyname('pOrigem').AsString := pOrigem;
             end;
             execsql;
        end;
     except
        on E: Exception do
           showmessageN('Erro ao executar script!'+E.Message);
     end;
     Ficha.Free;
end;




end.
