unit frmDMDespacho;

interface

uses
  System.SysUtils, System.Classes, DB, MemDS, DBAccess, MSAccess;

type
  TdmDespacho = class(TDataModule)
    PLI: TMSQuery;
    PLIRegistro: TIntegerField;
    PLIData: TDateTimeField;
    PLINumero: TStringField;
    PLIAplicacao: TSmallintField;
    PLISubstituida: TBooleanField;
    PLILI_Referencia: TStringField;
    PLINumero_PEXPAM: TStringField;
    PLIEmpresa: TSmallintField;
    dsPLI: TDataSource;
    PLIItens: TMSQuery;
    IntegerField1: TIntegerField;
    DateTimeField1: TDateTimeField;
    StringField1: TStringField;
    SmallintField1: TSmallintField;
    BooleanField1: TBooleanField;
    StringField2: TStringField;
    StringField3: TStringField;
    SmallintField2: TSmallintField;
    dsPLIItens: TDataSource;
    DI: TMSQuery;
    dsDI: TDataSource;
    OrgaosSRF: TMSQuery;
    dsOrgaosSRF: TDataSource;
    OrgaosSRFCodigo: TSmallintField;
    OrgaosSRFOrgao: TStringField;
    OrgaosSRFRecinto: TStringField;
    OrgaosSRFSetor: TStringField;
    OrgaosSRFDescricao: TStringField;
    RecintosAduaneiros: TMSQuery;
    dsRecintosAduaneiros: TDataSource;
    DIRegistro: TIntegerField;
    DISituacao: TStringField;
    DIProcesso: TStringField;
    DIData: TDateTimeField;
    DIDI: TStringField;
    DIQtde_Adicao: TSmallintField;
    DITipo_Declaracao: TSmallintField;
    DIMotivo_Trans: TSmallintField;
    DITipo_Importador: TSmallintField;
    DIModalidade_Despacho: TSmallintField;
    DIFUNDAP: TBooleanField;
    DIURF_Entrega: TStringField;
    DIURF_Despacho: TStringField;
    DIModalidade_Importacao: TSmallintField;
    DIConsignatario: TSmallintField;
    DIPais_Procedencia: TSmallintField;
    DIVia_Transporte: TSmallintField;
    DIMultimodal: TBooleanField;
    DINumero_Veiculo: TStringField;
    DINome_Veiculo: TStringField;
    DITipo_DocCarga: TSmallintField;
    DINumero_DocCarga: TStringField;
    DINumero_DocCargaMaster: TStringField;
    DILocal_Embarque: TStringField;
    DIData_Embarque: TDateTimeField;
    DIPeso_Bruto: TBCDField;
    DIPeso_Liquido: TBCDField;
    DIData_Chegada: TDateTimeField;
    DITipo_Manifesto: TSmallintField;
    DINumero_Manifesto: TStringField;
    DIRecinto_Aduaneiro: TStringField;
    DIFrete_PrePaid: TBCDField;
    DIFrete_Collect: TBCDField;
    DIFrete_Real: TBCDField;
    DIMoeda_Frete: TSmallintField;
    DISeguro_ME: TBCDField;
    DISeguro_Real: TBCDField;
    DIMoeda_Seguro: TSmallintField;
    DIDespesas_ME: TBCDField;
    DIMoeda_Despesas: TSmallintField;
    DIDespesas_Real: TBCDField;
    DITotal_MercadoriaME: TBCDField;
    DIOrigem_DI: TSmallintField;
    DISequencia_Retificacao: TSmallintField;
    DINumero_Retificacao: TSmallintField;
    DITipo_Pagamento: TSmallintField;
    DIBanco: TSmallintField;
    DIModalidade_Desc: TStringField;
    TiposDeclaracao: TMSQuery;
    dsTiposDeclaracao: TDataSource;
    TiposDeclaracaoCodigo: TSmallintField;
    TiposDeclaracaoDescricao: TStringField;
    DITipo_DeclaracaoDesc: TStringField;
    DIPais_Nome: TStringField;
    PO: TMSQuery;
    dsPO: TDataSource;
    PORegistro: TIntegerField;
    PONumero: TStringField;
    POProcesso: TStringField;
    POData: TDateTimeField;
    POExportador: TSmallintField;
    PORequisitante: TStringField;
    POVia_Transporte: TSmallintField;
    POLocal_Embarque: TStringField;
    POLocal_Entrega: TStringField;
    POINCOTERMS: TStringField;
    POCondicao_Cambial: TSmallintField;
    POMoeda: TSmallintField;
    POObservacao: TMemoField;
    POEmpresa: TSmallintField;
    POPais_Origem: TStringField;
    SLI: TMSQuery;
    dsSLI: TDataSource;
    SLIRegistro: TIntegerField;
    SLINumero: TStringField;
    SLIProcesso: TStringField;
    SLIInvoice: TStringField;
    SLIPais_Procedencia: TStringField;
    SLIURF_Despacho: TStringField;
    SLIURF_Entrada: TStringField;
    SLIInf_Complem: TMemoField;
    SLITipo_Fornecedor: TSmallintField;
    SLIExportador: TSmallintField;
    SLICondicao_Mercadoria: TSmallintField;
    SLIMoeda: TSmallintField;
    SLIINCOTERMS: TStringField;
    SLINCM: TStringField;
    SLIProcesso_Anuente: TStringField;
    SLIOrgao_Anuente: TStringField;
    SLIDrawBack: TSmallintField;
    SLIRegime_Tributacao: TSmallintField;
    SLIFundamento_Legal: TSmallintField;
    SLIAcordo_Tarifario: TStringField;
    SLICobertura_Cambial: TSmallintField;
    SLIModalidade_Pgto: TSmallintField;
    SLIDias_LimitePgto: TSmallintField;
    UnidadesRFB: TMSQuery;
    dsUnidadesRFB: TDataSource;
    UnidadesRFBCodigo: TStringField;
    UnidadesRFBDescricao: TStringField;
    OrgaosAnuentes: TMSQuery;
    dsOrgaosAnuentes: TDataSource;
    OrgaosAnuentesCodigo: TStringField;
    OrgaosAnuentesDescricao: TStringField;
    OrgaosAnuentesCNPJ: TStringField;
    RegimeTributacao: TMSQuery;
    dsRegimeTributacao: TDataSource;
    RegimeTributacaoCodigo: TSmallintField;
    RegimeTributacaoDescricao: TStringField;
    ModalidadesRFB: TMSQuery;
    dsModalidadesRFB: TDataSource;
    ModalidadesRFBCodigo: TSmallintField;
    ModalidadesRFBDescricao: TStringField;
    Financiadora: TMSQuery;
    dsFinanciadora: TDataSource;
    FinanciadoraCodigo: TSmallintField;
    FinanciadoraDescricao: TStringField;
    SLIFinanciadora: TSmallintField;
    MotivoCambial: TMSQuery;
    dsMotivoCambial: TDataSource;
    MotivoCambialCodigo: TSmallintField;
    MotivoCambialDescricao: TStringField;
    SLIMotivo_ImpCambial: TSmallintField;
    SLIItens: TMSQuery;
    dsSLIItens: TDataSource;
    SLIItensRegistro: TIntegerField;
    SLIItensLI: TStringField;
    SLIItensCodigo_Mercadoria: TIntegerField;
    SLIItensPeso_Liquido: TBCDField;
    SLIItensQtde_UnidadeCom: TBCDField;
    SLIItensQtde_MedidaEst: TBCDField;
    SLIItensValor_LocEmbarque: TBCDField;
    SLIItensValor_CondVenda: TBCDField;
    SLIItensItem: TSmallintField;
    SLIItensNCM: TStringField;
    SLIItensSLI: TIntegerField;
    SLIItensDescricao: TWideStringField;
    SLIFornecedor_Nome: TStringField;
    POModalidade_Importacao: TSmallintField;
    POResponsavel: TStringField;
    POCliente: TSmallintField;
    ViaTransporte: TMSQuery;
    dsViaTransporte: TDataSource;
    ViaTransporteCodigo: TSmallintField;
    ViaTransporteDescricao: TStringField;
    POTipo_Mercadoria: TSmallintField;
    POExportador_Nome: TStringField;
    AnuenteImp: TMSQuery;
    dsAnuenteImp: TDataSource;
    AnuenteImpCodigo: TSmallintField;
    AnuenteImpAbrev: TStringField;
    AnuenteImpNome: TStringField;
    AnuenteExp: TMSQuery;
    dsAnuenteExp: TDataSource;
    AnuenteExpCodigo: TSmallintField;
    AnuenteExpAbrev: TStringField;
    AnuenteExpNome: TStringField;
    RecintosAduaneirosCodigo: TIntegerField;
    RecintosAduaneirosDescricao: TStringField;
    ViaEspecialTransp: TMSQuery;
    dsViaEspecialTransp: TDataSource;
    ViaEspecialTranspCodigo: TSmallintField;
    ViaEspecialTranspDescricao: TStringField;
    EnquadramentoOper: TMSQuery;
    dsEnquadramentoOper: TDataSource;
    EnquadramentoOperCodigo: TStringField;
    EnquadramentoOperDescricao: TStringField;
    EnquadramentoOperIndicador_REVinculado: TBooleanField;
    EnquadramentoOperIndicador_DIVinculado: TBooleanField;
    EnquadramentoOperIndicador_NumProcesso: TBooleanField;
    EnquadramentoOperIndicador_NumRC: TBooleanField;
    EnquadramentoOperIndicador_NumRV: TBooleanField;
    EnquadramentoOperIndicador_PrazoPgto: TBooleanField;
    EnquadramentoOperIndicador_DSIVinculada: TBooleanField;
    EnquadramentoOperIndicador_CertifOrigem: TBooleanField;
    EnquadramentoOperTipo_Enquadramento: TStringField;
    EnquadramentoOperTipo_EnquadramentoDescr: TStringField;
    DIAcrescimo: TMSQuery;
    dsDIAcrescimo: TDataSource;
    DIAcrescimoDI: TStringField;
    DIAcrescimoCodigo: TSmallintField;
    DIAcrescimoMoeda: TIntegerField;
    Acrescimos: TMSQuery;
    dsAcrescimos: TDataSource;
    AcrescimosCodigo: TSmallintField;
    AcrescimosDescricao: TStringField;
    DIAcrescimoDescricao: TStringField;
    DIAcrescimoMoeda_Nome: TStringField;
    DIAcrescimoRegistro: TIntegerField;
    DIAdicoes: TMSQuery;
    dsDIAdicoes: TDataSource;
    DIAdicoesRegistro: TIntegerField;
    DIAdicoesDI: TStringField;
    DIAdicoesLI: TStringField;
    DIAdicoesAdicao: TSmallintField;
    DIAdicoesNCM: TStringField;
    DIAdicoesNBM: TStringField;
    DIAdicoesNALADI_SH: TStringField;
    DIAdicoesVia_Transporte: TSmallintField;
    DIAdicoesExportador: TSmallintField;
    DIAdicoesFabricante: TSmallintField;
    DIAdicoesPais_Aquisicao: TSmallintField;
    DIAdicoesPais_Procedencia: TSmallintField;
    DIAdicoesPais_Origem: TSmallintField;
    DIAdicoesTipo_Fabricante: TSmallintField;
    DIAdicoesPeso_Liquido: TBCDField;
    DIAdicoesQuantidade: TBCDField;
    DIAdicoesMoeda_FOB: TSmallintField;
    DIAdicoesMoeda_Frete: TSmallintField;
    DIAdicoesMoeda_Seguro: TSmallintField;
    DIAdicoesMoeda_Despesas: TSmallintField;
    DIAdicoesINCOTERMS: TStringField;
    DIAdicoesLocal_CondicaoVenda: TStringField;
    DIAdicoesValor_Frete: TBCDField;
    DIAdicoesParidade: TBCDField;
    DIAdicoesTaxa_Cambio: TBCDField;
    DIAdicoesValor_Seguro: TBCDField;
    DIAdicoesMetodo_Valoracao: TSmallintField;
    DIAdicoesVinculo_CompVend: TSmallintField;
    DIAdicoesAcordo_ALADI: TSmallintField;
    DIAdicoesFundamento_Legal: TSmallintField;
    DIAdicoesDocumento_Reducao: TStringField;
    DIAdicoesValor_MercadoriaME: TBCDField;
    DIAdicoesValor_DespesasME: TBCDField;
    DIAdicoesPercentual_RedII: TBCDField;
    DIAdicoesValor_II: TBCDField;
    DIAdicoesValor_IIZFM: TBCDField;
    DIAdicoesCobertura_Cambial: TSmallintField;
    DIAdicoesModalidade_Pgto: TSmallintField;
    DIAdicoesOrgao_Financiador: TSmallintField;
    DIAdicoesMotivo_SemCobertura: TSmallintField;
    DIAdicoesQuantidade_ParcFin: TSmallintField;
    DIAdicoesIntervalo_Parcela: TSmallintField;
    DIAdicoesValor_TotalPrazo: TBCDField;
    DIAdicoesTaxa_Juros: TBCDField;
    DIAdicoesTaxa_JurosCodigo: TSmallintField;
    DIAdicoesValor_TotalFin: TBCDField;
    DIAdicoesNumero_ROF: TStringField;
    DIAdicoesPagamento_Variavel: TBooleanField;
    DIAdicoesIncidencia_Juros: TBooleanField;
    DIAdicoesPercentual_Comissao: TBCDField;
    DIAdicoesValor_Comissao: TBCDField;
    DIAdicoesAgente: TSmallintField;
    DIAdicoesEncomenda: TBooleanField;
    DIAdicoesUsado: TBooleanField;
    DIAdicoesComplemento: TMemoField;
    DIAdicoesMotivo_Admissao: TSmallintField;
    DIAdicoesValor_DCRME: TBCDField;
    DIAdicoesAliquota_ICMS: TBCDField;
    DIAdicoesFundamento_LegalReduc: TSmallintField;
    DIAdicoesRegime_PIS: TSmallintField;
    DIAdicoesFundamento_LegalPIS: TSmallintField;
    DIAdicoesTipo_Certificado: TSmallintField;
    DIAdicoesFabricante_Nome: TStringField;
    DIAdicoesRelacao_ExpFab: TSmallintField;
    DIAdicoesPeso_Bruto: TBCDField;
    DIAdicoesAliquota_COFINS: TBCDField;
    DIAdicoesAliquota_PIS: TBCDField;
    DIIndicativo_Conhec: TSmallintField;
    DIVolumes: TStringField;
    DIAdicoesValor_MercadoriaReal: TBCDField;
    DIAdicoesAliquota_RedCOFINS: TBCDField;
    MetodoVal: TMSQuery;
    dsMetodoVal: TDataSource;
    MetodoValCodigo: TSmallintField;
    MetodoValDescricao: TStringField;
    DIAdicoesMetodo_ValNome: TStringField;
    AgFinanciadora: TMSQuery;
    dsAgFinanciadora: TDataSource;
    AgFinanciadoraCodigo: TSmallintField;
    AgFinanciadoraDescricao: TStringField;
    DIAdicoesFinanciadora: TSmallintField;
    DIAdicoesAplicacao: TStringField;
    DIAdicoesNALADI_NCCA: TStringField;
    DIAdicoesURF_Entrega: TStringField;
    DIAdicoesCondicao_Mercadoria: TStringField;
    DIAdicoesUnidade: TStringField;
    DIAdicoesAcordo_TarifarioIICod: TSmallintField;
    DIAdicoesAliquota_II: TBCDField;
    DIAdicoesAliquota_ReducaoII: TBCDField;
    DIAdicoesII_Reduzida: TBCDField;
    DIAcrescimoValor_ME: TBCDField;
    DIAcrescimoValor_Real: TBCDField;
    AdicoesAcre: TMSQuery;
    dsAdicaoAcre: TDataSource;
    AdicoesAcreRegistro: TIntegerField;
    AdicoesAcreDI: TStringField;
    AdicoesAcreAdicao: TIntegerField;
    AdicoesAcreCodigo: TSmallintField;
    AdicoesAcreMoeda: TSmallintField;
    AdicoesAcreValor_ME: TBCDField;
    AdicoesAcreValor_Real: TBCDField;
    DITotal_AcrescimoReal: TBCDField;
    FundamentoLegal: TMSQuery;
    dsFundamentoLegal: TDataSource;
    FundamentoLegalCodigo: TSmallintField;
    FundamentoLegalDescricao: TStringField;
    DIFundamento_Legal: TSmallintField;
    DIMotivo_AdmissaoTemp: TSmallintField;
    MotivoAdmissaoTemp: TMSQuery;
    dsMotivoAdmissaoTemp: TDataSource;
    MotivoAdmissaoTempCodigo: TSmallintField;
    MotivoAdmissaoTempDescricao: TStringField;
    DIAdicoesValor_BCII: TBCDField;
    DIAdicoesAliquota_IPI: TBCDField;
    DIAdicoesValor_BCIPI: TBCDField;
    DIAdicoesValor_IPI: TBCDField;
    DIAdicoesValor_BCPIS: TBCDField;
    DIAdicoesValor_PIS: TBCDField;
    DIAdicoesValor_BCCOFINS: TBCDField;
    DIAdicoesValor_COFINS: TBCDField;
    DIAdicoesValor_BCICMS: TBCDField;
    DIAdicoesValor_ICMS: TBCDField;
    DIAdicoesAliquota_RedPIS: TBCDField;
    DIAdicoesAliquota_IPIEspRec: TBCDField;
    DIAdicoesAliquota_IPIEspUnid: TBCDField;
    RegTribBCPIS: TMSQuery;
    dsRegTribBCPIS: TDataSource;
    RegTribBCPISCodigo: TSmallintField;
    RegTribBCPISDescricao: TStringField;
    DIAdicoesReducao_BCPISCOFINS: TBCDField;
    DIRecinto_AduaneiroSetor: TSmallintField;
    DITipo_Conhecimento: TSmallintField;
    DIDocumento_Chegada: TStringField;
    DIAgente_Transportador: TStringField;
    DIAdicoesRegime_TribII: TSmallintField;
    DIAgente_Numero: TStringField;
    DocInstrucao: TMSQuery;
    dsDocInstrucao: TDataSource;
    DocInstrucaoCodigo: TSmallintField;
    DocInstrucaoDescricao: TStringField;
    DIDocumentos: TMSQuery;
    dsDIDocumentos: TDataSource;
    DIDocumentosDI: TStringField;
    DIDocumentosCodigo: TSmallintField;
    DIDocumentosNumero: TStringField;
    DIDocumentosDescricao: TStringField;
    Embalagens: TMSQuery;
    dsEmbalagens: TDataSource;
    EmbalagensCodigo: TSmallintField;
    EmbalagensDescricao: TStringField;
    DITipo_Embalagem: TSmallintField;
    DIVolumes_Embalagem: TSmallintField;
    DIFrete_TerritorioNac: TBCDField;
    DITotal_MercadoriaReal: TBCDField;
    DIRegime_TributacaoII: TSmallintField;
    DIAdicoesRegime_Tributario: TSmallintField;
    DIAdicoesAcordo_TarifarioII: TSmallintField;
    POItens: TMSQuery;
    dsPOItens: TDataSource;
    POItensRegistro: TIntegerField;
    POItensPO: TStringField;
    POItensCodigo_Mercadoria: TSmallintField;
    POItensItem: TSmallintField;
    POItensQuantidade: TBCDField;
    POItensValor: TBCDField;
    POItensQuantidade_Unidade: TBCDField;
    POItensQuantidade_Volumes: TBCDField;
    POItensNCM: TStringField;
    POItensFabricante: TSmallintField;
    POItensSel: TBooleanField;
    POItensSaldo: TBCDField;
    POItensDescricao: TStringField;
    procedure POItensCalcFields(DataSet: TDataSet);
    procedure POItensBeforePost(DataSet: TDataSet);
    procedure POItensDescricaoGetText(Sender: TField; var Text: string; DisplayText: Boolean);
    procedure POItensDescricao_CompletaGetText(Sender: TField; var Text: string; DisplayText: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dmDespacho: TdmDespacho;

implementation

uses frmDados, FUNCOES;

{$R *.dfm}

procedure TdmDespacho.POItensCalcFields(DataSet: TDataSet);
begin
      DataSet.FieldByName('Total').Value := DataSet.FieldByName('Valor').Value * DataSet.FieldByName('Quantidade').Value;
end;

procedure TdmDespacho.POItensDescricaoGetText(Sender: TField; var Text: string; DisplayText: Boolean);
begin
      if not Sender.IsNull then begin
         Text := RemoveCaracter(#13,'',Sender.AsString);
         Text := RemoveCaracter(#12,'',Text);
         Text := RemoveCaracter(#10,'',Text);
         Text := RemoveCaracter('<{'+POItensCodigo_Mercadoria.AsString+'}>' ,'',Text);
      end;
end;

procedure TdmDespacho.POItensDescricao_CompletaGetText(Sender: TField; var Text: string; DisplayText: Boolean);
begin
      If not Sender.IsNull then begin
         Text := RemoveCaracter(#13,'',Sender.AsString);
         Text := RemoveCaracter(#12,'',Text);
         Text := RemoveCaracter(#10,'',Text);
         Text := RemoveCaracter('<{'+POItensCodigo_Mercadoria.AsString+'}>' ,'',Text);
      End;
end;

procedure TdmDespacho.POItensBeforePost(DataSet: TDataSet);
begin
      LogDados(DataSet, '('+POItensRegistro.AsString+') Nº '+POItensPO.AsString+' Item:'+POItensItem.AsString+'  Produto:'+POItensCodigo_Mercadoria.asstring, DataSet.State);
end;



end.
